### ISSUE TITLE
Tests don't pass in raw environment

### ISSUE THREAD

**Issue by Prestaul** [selfcontained/flipflop#1]
Cloned the repo, ran `npm install`, then `npm test`, and half the tests seem to fail.  Does it require that directories are already created?  Do tests require that flipflop is installed globally through npm or can I run it from a development clone of the repo?  Are unit tests designed to test a flipflop site, or flipflop itself?

Here is my output:

```
> npm test

> flipflop@0.0.3 test /Users/mdunlap/Sites/nodes/flipflop
> vows

·······✗✗✗✗✗✗✗✗✗✗✗✗✗  


    When using flipflop generate 
      ✗ public directory exists 
        » expected true, got false // commands.test.js:57 

      ✗ archive exists 
        » expected true, got false // commands.test.js:60 

      ✗ feed exists 
        » expected true, got false // commands.test.js:63 

      ✗ 404 page exists 
        » expected true, got false // commands.test.js:66 

      ✗ images directory exists 
        » expected true, got false // commands.test.js:69 

      ✗ tag directory exists 
        » expected true, got false // commands.test.js:72 

      ✗ sample article exists 
        » expected true, got false // commands.test.js:82 

    When using flipflop start and requesting homepage 
      ✗ has response 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 

      ✗ body is correct 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 

    When using flipflop start and requesting archive 
      ✗ has response 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 

      ✗ body is correct 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 

    When using flipflop start and requesting feed 
      ✗ has response 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 

      ✗ body is correct 
        » expected null, got { 
      arguments: undefined, 
      code: 'ECONNREFUSED', 
      type: undefined, 
      syscall: 'connect', 
      errno: 'ECONNREFUSED', 
      message: 'connect ECONNREFUSED', 
      stack: 'Error: connect ECONNREFUSED\n    at errnoException (net.js:646:11)\n    at Object.afterConnect [as oncomplete] (net.js:637:18)' 
  } // net.js:646 
  ✗ Broken » 7 honored ∙ 13 broken (0.086s)
```

**Comment by selfcontained** [comment]
Thanks for checking it out Matt.  Any chance you can dump the output of `npm ls` from your dev dir of flipflop?  I tried it on a new machine and didn't run into any issues.  Perhaps there's a dependency issue.  

As far as your questions:
- _Does it require that directories are already created?_
  
  **No, everything is self-contained in the `test` folder**
- _Do tests require that flipflop is installed globally through npm or can I run it from a development clone of the repo?_
  
  **No, the tests don't use the flipflop binary, running from a clone of the repo should suffice.**
- _Are unit tests designed to test a flipflop site, or flipflop itself?_
  
  **They test flipflop itself, not a site.  During the tests they do actually create a site inside an `artifact` folder within the `test` folder.**

**Comment by Prestaul** [comment]
I should have mentioned that I tried tracing missing dependencies last night...

```
npm WARN connect 1.x Unmet dependency in /Users/mdunlap/Sites/nodes/flipflop/node_modules/express
npm WARN async 0.1.x Unmet dependency in /Users/mdunlap/Sites/nodes/flipflop/node_modules/winston
npm WARN stack-trace 0.0.x Unmet dependency in /Users/mdunlap/Sites/nodes/flipflop/node_modules/winston
```

I'm not sure what is going on with this, but I can't get npm to resolve these three dependencies...

**Comment by Prestaul** [comment]
Ok, I jumped through some hoops (like installing old versions of modules and then npm updating them to current versions) and now I have a more reasonable state:

```
> npm ls
flipflop@0.0.3 /Users/mdunlap/Sites/nodes/flipflop
├── async@0.1.18  extraneous
├── colors@0.6.0-1 
├─┬ connect@1.8.7  extraneous
│ ├── formidable@1.0.9 
│ ├── mime@1.2.5 
│ └── qs@0.5.0 
├─┬ express@2.5.9 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.3.0 
│ └── qs@0.4.2 
├─┬ flatiron@0.1.16 
│ ├─┬ broadway@0.1.14 
│ │ ├─┬ cliff@0.1.7 
│ │ │ └── eyes@0.1.7 
│ │ ├── colors@0.6.0-1 
│ │ ├── eventemitter2@0.4.9 
│ │ ├─┬ nconf@0.5.1 
│ │ │ ├── async@0.1.18 
│ │ │ ├── ini@1.0.2 
│ │ │ └── pkginfo@0.2.3 
│ │ ├─┬ optimist@0.3.1 
│ │ │ └── wordwrap@0.0.2 
│ │ ├─┬ utile@0.0.10 
│ │ │ ├── async@0.1.18 
│ │ │ ├── mkdirp@0.3.2 
│ │ │ ├── ncp@0.2.6 
│ │ │ └── rimraf@1.0.9 
│ │ └─┬ winston@0.5.10 
│ │   ├── async@0.1.18 
│ │   ├── eyes@0.1.7 
│ │   ├─┬ loggly@0.3.11 
│ │   │ ├── request@2.9.202 
│ │   │ └── timespan@2.2.0 
│ │   ├── pkginfo@0.2.3 
│ │   └── stack-trace@0.0.6 
│ ├── director@1.0.9-1 
│ ├─┬ optimist@0.3.1 
│ │ └── wordwrap@0.0.2 
│ ├── pkginfo@0.2.3 
│ └─┬ prompt@0.1.12 
│   ├── async@0.1.18 
│   ├── colors@0.6.0-1 
│   ├── pkginfo@0.2.3 
│   └─┬ winston@0.5.11 
│     ├── eyes@0.1.7 
│     ├─┬ loggly@0.3.11 
│     │ ├── request@2.9.202 
│     │ └── timespan@2.2.0 
│     └── stack-trace@0.0.6 
├── highlight@0.2.1 
├─┬ jade@0.22.1 
│ ├── commander@0.5.2 
│ └── mkdirp@0.3.0 
├── less@1.3.0 
├── marked@0.2.4 
├── moment@1.5.1 
├── request@2.9.202 
├── stack-trace@0.0.5  extraneous
├─┬ utile@0.0.10 
│ ├── async@0.1.18 
│ ├── mkdirp@0.3.2 
│ ├── ncp@0.2.6 
│ └── rimraf@1.0.9 
├─┬ vows@0.6.2 
│ └── eyes@0.1.7 
├─┬ winston@0.5.11 
│ ├── eyes@0.1.7 
│ ├─┬ loggly@0.3.11 
│ │ ├── request@2.9.202 
│ │ └── timespan@2.2.0 
│ └── pkginfo@0.2.3 
└── wrench@1.3.8
```

But now it is complaining that it cannot find `utile` although it is clearly installed... What's the deal?!

```
> npm test

> flipflop@0.0.3 test /Users/mdunlap/Sites/nodes/flipflop
> vows

·······/Users/mdunlap/Sites/nodes/flipflop/test/artifacts/articles
info:   Generating:      /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public
info:   Created directory:   /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public
info:   Copied static files:     /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/404.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/index.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/2012/05/08/flipflop-ftw/index.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/archive/index.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/feed/rss.xml
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/tag/flipflop/index.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/tag/javascript/index.html
info:   created file:        /Users/mdunlap/Sites/nodes/flipflop/test/artifacts/public/tag/node.js/index.html
·······/Users/mdunlap/Sites/nodes/flipflop/test/artifacts/articles

module.js:311
    throw err;
          ^
Error: Cannot find module './utils'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/mdunlap/Sites/nodes/flipflop/node_modules/express/node_modules/connect/lib/http.js:16:13)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

npm ERR! flipflop@0.0.3 test: `vows`
npm ERR! `sh "-c" "vows"` failed with 1
npm ERR! 
npm ERR! Failed at the flipflop@0.0.3 test script.
npm ERR! This is most likely a problem with the flipflop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vows
npm ERR! You can get their info via:
npm ERR!     npm owner ls flipflop
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "test"
npm ERR! cwd /Users/mdunlap/Sites/nodes/flipflop
npm ERR! node -v v0.6.13
npm ERR! npm -v 1.1.9
npm ERR! code ELIFECYCLE
npm ERR! message flipflop@0.0.3 test: `vows`
npm ERR! message `sh "-c" "vows"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mdunlap/Sites/nodes/flipflop/npm-debug.log
npm not ok
```

**Comment by selfcontained** [comment]
It says `Error: Cannot find module './utils'` - is that coming from connect?  I wonder if I need to look @ `npm shrinkwrap`

**Comment by Prestaul** [comment]
Well... Getting _connect_ installed was easy (although I'm still not sure why I had to do it manually) but it still didn't work because the requirement was for an old version.  After a `npm install connect@1.x` things seemed better, but tests still wouldn't run...

**Comment by Prestaul** [comment]
Any idea why those three items that did not install automatically?  After pulling some en-pee-em-acrobatics I got them installed locally but they are still marked as "extraneous"...

**Comment by selfcontained** [comment]
dunno off the top of my head.  Less dependencies may simplify things, but I don't know that would resolve whatever this issue is.  I'd like to remove connect/express as dependencies but need to do some work to convert some of the structure to be Broadway compatible.

**Comment by selfcontained** [comment]
`npm ls` on a clean machine (node didn't even exist on it prior) after a `git clone` and `npm install`

```
>npm ls

flipflop@0.0.3 /Users/bmharris/workspace/flipflop
├── colors@0.6.0-1 
├─┬ express@2.5.9 
│ ├─┬ connect@1.8.7 
│ │ └── formidable@1.0.9 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.3.0 
│ └── qs@0.4.2 
├─┬ flatiron@0.1.16 
│ ├─┬ broadway@0.1.14 
│ │ ├─┬ cliff@0.1.7 
│ │ │ └── eyes@0.1.7 
│ │ ├── eventemitter2@0.4.9 
│ │ ├─┬ nconf@0.5.1 
│ │ │ ├── async@0.1.18 
│ │ │ └── ini@1.0.2 
│ │ └─┬ winston@0.5.10 
│ │   ├── async@0.1.18 
│ │   ├── eyes@0.1.7 
│ │   ├─┬ loggly@0.3.11 
│ │   │ └── timespan@2.2.0 
│ │   └── stack-trace@0.0.6 
│ ├── director@1.0.9-1 
│ ├─┬ optimist@0.3.1 
│ │ └── wordwrap@0.0.2 
│ ├── pkginfo@0.2.3 
│ └─┬ prompt@0.1.12 
│   └── async@0.1.18 
├── highlight@0.2.1 
├─┬ jade@0.22.1 
│ ├── commander@0.5.2 
│ └── mkdirp@0.3.0 
├── less@1.3.0 
├── marked@0.2.4 
├── moment@1.5.1 
├── request@2.9.202 
├─┬ utile@0.0.10 
│ ├── async@0.1.18 
│ ├── mkdirp@0.3.2 
│ ├── ncp@0.2.6 
│ └── rimraf@1.0.9 
├─┬ vows@0.6.2 
│ └── eyes@0.1.7 
├─┬ winston@0.5.11 
│ ├── async@0.1.18 
│ ├── eyes@0.1.7 
│ ├─┬ loggly@0.3.11 
│ │ └── timespan@2.2.0 
│ ├── pkginfo@0.2.3 
│ └── stack-trace@0.0.6 
└── wrench@1.3.8 
```

**Comment by Prestaul** [comment]
Did the tests run correctly on the clean install?

Maybe it is because I already had `connect`, `stack-trace`, and `winston` installed globally prior to installing `flipflop`?

**Comment by Prestaul** [comment]
Although, I guess the same was true for nconf, vows, jade, highlight, etc... Why did those three not install and why can node not find utile?   hmmm...

**Comment by selfcontained** [comment]
yup, tests passed w/ clean install
